# Generated by Django 4.1.1 on 2022-10-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yozuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('job', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=30)),
                ('sana', models.DateTimeField(blank=True, default=None, null=True)),
                ('mavzu', models.CharField(max_length=30)),
                ('math', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.yozuvchi')),
            ],
        ),
    ]
