# Generated by Django 4.1.1 on 2022-10-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='mavzu',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='sarlavha',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yozuvchi',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yozuvchi',
            name='job',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yozuvchi',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
